- name: Установка Nginx
  hosts: frontend_server
  roles:
    - frontend

- name: Установка PostgreSQL
  hosts: postgresql
  roles:
    - postresql   

- name: Установка Django и Gunicorn
  hosts: backend_server
  roles:
    - backend
